#!/bin/bash

PREFIX="\033[44m\033[1mINFO  \033[0m "
PREFIX_ERR="\033[41m\033[1mERROR \033[0m \033[31m"
PREFIX_DONE="\033[42m\033[1mDONE  \033[0m \033[32m"

# Helper functions
clog() {
	echo -e "${PREFIX}$*\033[0m"
}

cerr() {
	echo -e "${PREFIX_ERR}$*\033[0m"
}

cdone() {
	echo -e "${PREFIX_DONE}$*\033[0m"
}

q() {
	OUTPUT=$("$@" 2>&1)
	STATUS=$?
	if [ $STATUS -ne 0 ]; then
		cerr "An error has occurred:"
		echo "$OUTPUT"
		exit $STATUS
	fi
}
