#!/usr/bin/env python3

import sys
import os
import subprocess

LOGO = r"""
┌────────────────────────────────────────┐
│  _  _        _              __!__      │
│ / \|_) _ __ |_| o  __   _____(_)_____  │
│ \_/|  (/_| || | |  |       !  !  !     │
└────────────────────────────────────────┘
"""

DIM = "\033[2m"
CYAN = "\033[36m"
WHITE = "\033[37m"
RESET = "\033[0m"
BOLD = "\033[1m"

LOGO_COLOR = f"""
{DIM}┌────────────────────────────────────────┐
│  {RESET}{CYAN}_  _        {BOLD}_              {WHITE}__!__      {RESET}{WHITE}{DIM}│
│ {RESET}{CYAN}/ \\|_) _ __ {BOLD}|_| o  __  {WHITE} _____(_)_____  {RESET}{WHITE}{DIM}│
│ {RESET}{CYAN}\\_/|  (/_| |{BOLD}| | |  |       {WHITE}!  !  !     {RESET}{WHITE}{DIM}│
└────────────────────────────────────────┘
{RESET}"""


COMMAND_TREE = {
    "build": {
        "__exec__": "./tools/build/build.sh",
    },
    "run": {
        "__exec__": "",
        "server": {"__exec__": "./tools/dev/startserver.sh"},
        "client": {"__exec__": "./tools/dev/startclient.sh"},
    },
    "setup": {"mac": {"__exec__": "./tools/setup/mac.sh"}},
    "__exec__": None,
}

SYSTEM_MAJOR = sys.version_info.major
SYSTEM_MINOR = sys.version_info.minor

EXPECTED_MAJOR = int(os.environ.get("EXPECTED_MAJOR"))
EXPECTED_MINOR = int(os.environ.get("EXPECTED_MINOR"))

if EXPECTED_MAJOR != SYSTEM_MAJOR or EXPECTED_MINOR > SYSTEM_MINOR:
    print(
        f"\033[31mPython {EXPECTED_MAJOR} minor >={EXPECTED_MINOR} expected, but found {SYSTEM_MAJOR}.{SYSTEM_MINOR}\033[0m"
    )
    exit(1)


curr: dict | None = COMMAND_TREE
for arg in sys.argv[1:]:
    if arg in curr:
        curr = curr[arg]

    else:
        break
else:
    if "__exec__" in curr:
        print(LOGO_COLOR)
        if curr["__exec__"] is None:
            exit(0)
        try:
            subprocess.run(curr["__exec__"])
            exit(0)
        except KeyboardInterrupt:
            exit(0)

print(f"Unknown argument: {' '.join(sys.argv)}")
exit(1)
